server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Juandiego159/EXAMEN-MICROSERVICIOS-JCC-principal.git
          searchPaths: config-data
          default-label: principal
  security:
    user:
      name: 
      password: paricahua
